import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";

import Header from './components/Header/';

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={karla.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
