import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";

import Header from './components/Header/';
import Footer from './components/Footer/';

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meu Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/profile.jpeg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={karla.className}>
        <Header />
        <main className='content'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
